### ISSUE TITLE
Add `MakeFlatpak` Task to Packaging

### ISSUE THREAD

**Issue by nlogozzo** [NickvisionApps/CakeScripts#1]
@fsobolev Could you add a `MakeFlatpak` task to the packaging script that will generate a `.flatpak` file. 

This will be useful next week when GNOME 45 runtime is out and we need to update our app UI but won't have libadwaita 1.4 locally since Fedora 39 won't be released until later.

So I can just run `dotnet cake --target=MakeFlatpak` and get my `.flatpak` file to install and test.

**Comment by fsobolev** [comment]
> get my .flatpak file to install and test.

The problem with this idea is that creating a flatpak bundle and then installing it takes significant amount of time, it will be easier for you to just have GNOME Builder opened and switch to it after editing files in your IDE and run an app there.
But I will look how Builder runs the app without installing it and will try to replicate this.

**Comment by nlogozzo** [comment]
> But I will look how Builder runs the app without installing it and will try to replicate this.

That's be nice..but if not this:

> The problem with this idea is that creating a flatpak bundle and then installing it takes significant amount of time

is fine I don't mind the wait. Either that or I'll be manually triggering a lot of CI builds 😂 so I'll be waiting either way
